apiVersion: v1
kind: Service
metadata:
  name: qlcplus
  namespace: qlcplus
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dmx.svc.technotut.net
spec:
  selector:
    app: qlcplus
  type: LoadBalancer
  loadBalancerIP: 10.11.240.254
  ports:
  - name: artnet
    protocol: UDP
    port: 6454
    targetPort: 6454
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9999