apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam2-nginx-deployment
  labels:
    app: cam2-sonycam-nginx
  namespace: cam2
spec:
  selector:
    matchLabels:
      app: cam2-sonycam-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: cam2-sonycam-nginx
    spec:
      containers:
      - name: cam2-sonycam-nginx
        image: ghcr.io/technotut/sonycam-nginx:main
        env:
        - name: SERVER_URL
          value: rtmp://rtmp-service.live:1935/live/cam2
        ports:
        - containerPort: 1935
        - containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 256Mi
      restartPolicy: Always
status: {}