apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
  labels:
    app: rtmp-live-server
  namespace: live
  annotations:
    external-dns.alpha.kubernetes.io/hostname: live.kube.technotut.net
spec:
  selector:
    app: rtmp-live-server
  type: LoadBalancer
  loadBalancerIP: 10.33.70.0
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080