apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bind-svc-zone-pvc
  namespace: bind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
