apiVersion: v1
kind: Secret
metadata:
  name: bind-tsig
  namespace: bind
type: Opaque
stringData:
  externaldns.key: |
    key "externaldns" {
        algorithm hmac-sha256;
        secret "Tq/74pwBk4hTAJEMrtc8gr6ReE06OrK2qbHdhcSkSTA=";
    };
    