apiVersion: v1
kind: Service
metadata:
  name: coredns-service
  namespace: cam1
spec:
  type: LoadBalancer
  selector:
    k8s-app: coredns
  loadBalancerIP: 10.33.71.11
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP